Release: v1.2.7

diff --git a/.github/workflows/moodle-release.yml b/.github/workflows/moodle-release.yml
--- a/.github/workflows/moodle-release.yml
+++ b/.github/workflows/moodle-release.yml
@@ -35,9 +35,13 @@ jobs:
             echo "No tag name has been provided!"
             exit 1
           fi
-          echo "Tag name: ${TAGNAME}"  # Debug statement to print the tag name
+          echo "Tag name: ${TAGNAME}"
           ZIPURL="https://api.github.com/repos/${{ github.repository }}/zipball/${TAGNAME}"
-          echo "Zip URL: ${ZIPURL}"  # Debug statement to print the zip URL
+          echo "Zip URL: ${ZIPURL}"
+          
+          # Add a delay to ensure the ZIP is available
+          sleep 30
+          
           RESPONSE=$(${CURL} ${ENDPOINT} --data-urlencode "wstoken=${TOKEN}" \
                                          --data-urlencode "wsfunction=${FUNCTION}" \
                                          --data-urlencode "moodlewsrestformat=json" \
@@ -48,7 +52,7 @@ jobs:
                                          --data-urlencode "vcstag=${TAGNAME}" \
                                          --data-urlencode "changelogurl=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commits/${TAGNAME}" \
                                          --data-urlencode "altdownloadurl=${ZIPURL}")
-          echo "API Response: ${RESPONSE}"  # Debug statement to print the API response
+          echo "API Response: ${RESPONSE}"
           echo "response=${RESPONSE}" >> $GITHUB_ENV
       - name: Evaluate the response
         id: evaluate-response
@@ -56,5 +60,8 @@ jobs:
           RESPONSE: ${{ steps.add-version.outputs.response }}
         run: |
           echo "API Response: ${RESPONSE}"
-          jq <<< ${RESPONSE}
-          jq --exit-status ".id" <<< ${RESPONSE} > /dev/null
+          if echo "${RESPONSE}" | jq --exit-status ".id" > /dev/null; then
+            echo "API call successful."
+          else
+            echo "API call failed."
+            exit 1
